
create or replace view THRIVE_DB.ANALYTICS.CUSTOMER_TC_BALANCE(
	CUSTOMERID,
	TOTAL_EARNED,
	TOTAL_REDEEMED,
	CURRENT_BALANCE
) as
SELECT
    CUSTOMERID,
    SUM(CASE WHEN TCTYPE = 'earned' THEN AMOUNT ELSE 0 END) AS total_earned,
    SUM(CASE WHEN TCTYPE IN ('spent', 'expired') THEN ABS(AMOUNT) ELSE 0 END) AS total_redeemed,
    SUM(AMOUNT) AS current_balance
FROM THRIVE_DB.PROCESSED.TC_DATA_WITH_REDEMPTIONS
GROUP BY CUSTOMERID;
