
Fifo View1
SELECT * FROM THRIVE_DB.ANALYTICS.fifo_match_rate;
/*
CREATE OR REPLACE VIEW ANALYTICS.fifo_match_rate AS
SELECT
    COUNT(*) AS total_spent_transactions,
    COUNT(REDEEMID) AS matched_transactions,
    ROUND(COUNT(REDEEMID) / COUNT(*) * 100, 2) AS match_percentage
FROM PROCESSED.TC_DATA_WITH_REDEMPTIONS
WHERE TCTYPE IN ('spent', 'expired');
*/

-- Fifo dashboard View 2
SELECT *
FROM THRIVE_DB.PROCESSED.TC_DATA_WITH_REDEMPTIONS
WHERE TCTYPE IN ('spent','expired')
  AND REDEEMID IS NULL;


Sales Analytics 
SELECT C.FIRSTNAME, B.* FROM THRIVE_DB.ANALYTICS.CUSTOMER_TC_BALANCE AS B JOIN RAW_DATA.CUSTOMERS AS C
ON B.CUSTOMERID = C.CUSTOMERID

-- By Customer
WITH CTE_CUSTOMERS AS (
SELECT C.FIRSTNAME, B.* FROM THRIVE_DB.RAW_DATA.SALES AS B JOIN  THRIVE_DB.RAW_DATA.CUSTOMERS AS C
ON B.CUSTOMERID = C.CUSTOMERID
)
SELECT FIRSTNAME, SUM(PREDISCOUNTGROSSPRODUCTSALES) AS TOTAL_SALES, SUM(ORDERWEIGHT) AS TOTAL_WEIGHT FROM CTE_CUSTOMERS
GROUP BY FIRSTNAME
